export default {
  ADD_TO_CART: 'cart/ADD_TO_CART',
  ADD_TO_CART_SUCCESS: 'cart/ADD_TO_CART_SUCCESS',
  UPDATE_QUANTITY: 'cart/UPDATE_QUANTITY',
  UPDATE_QUANTITY_SUCCESS: 'cart/UPDATE_QUANTITY_SUCCESS',
  REMOVE_ITEM: 'cart/REMOVE_ITEM',
}
